spring:
  datasource:
    url: "${custom.dev.db.url}"
    username: "${custom.dev.db.username}"
    password: "${custom.dev.db.password}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "${custom.dev.jwt.secret}"
  access-expiration: 1800000
  refresh-expiration: 604800000

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always

app:
  cookie:
    secure: false
  cors:
    allowed-origins: http://localhost:3000

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_BUCKET}
      cloudfront-domain: ${CLOUDFRONT_DOMAIN}