spring:
  application:
    name: ovengers
  profiles:
    active: dev
    include: secret
  datasource:
    hikari:
      maximum-pool-size: 150
      connection-timeout: 30000


  servlet: #SSE 응답 깨짐 현상 해결
    encoding:
      charset: UTF-8
      force-response: true

go-camping:
  base-url: https://apis.data.go.kr/B551011/GoCamping
  endpoint:
    based-list: /basedList
    image-list: /imageList
  value:
    numOfRows: 1000
    mobileOS: ETC
    mobileApp: OVENGERS
    type: json

toss:
  secret-key: ${toss.secret-key}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
